version: "3"
services:
  mtml-test-api:
    image: mtml-test-api:v0.2
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
     - 8080:8080
    restart: always
    environment:
      - GIN_MODE=release
    volumes: 
     - ./images:/app/images
     - ./logs:/app/logs
    